version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!

    docker:
      - image: cimg/python:3.10.2

    steps:
        - checkout
        - run:
              name: Install Dependencies
              # This assumes pytest is installed via the install-package step above
              command: |
                python3 -m venv venv
                . venv/bin /activate
                pip install -r requirements.txt
        - run:
              name: run lint
              command: |
                . venv/bin/activate
                make lint

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
